version: '3.1'

services:
  newstelegram-bot:
    depends_on:
      - newstb-db
    build:
      context: .
    environment:
      - BOT_NAME=${BOT_NAME}
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_DB_USERNAME=${BOT_DB_USERNAME}
      - BOT_DB_PASSWORD=${BOT_DB_PASSWORD}
    restart: always
  newstb-db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - "5430:5432"
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB: