ALTER TABLE tg_user ADD PRIMARY KEY (chat_id);

CREATE TABLE topic (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_name VARCHAR(20) NOT NULL UNIQUE,
    active BOOLEAN
);

CREATE TABLE topic_x_user (
    topic_id INT NOT NULL,
    FOREIGN KEY (topic_id) REFERENCES topic(id),
    user_id VARCHAR(100) NOT NULL ,
    FOREIGN KEY (user_id) REFERENCES tg_user(chat_id),
    UNIQUE (user_id, topic_id)
);